# hpool start port
# port: 8090

mainnet:
  # http服务器端口
  httpPort: 8081

  # Zcash server host
  # zcashHost: http://192.168.1.79/
  zcashHost: http://39.104.136.10/

  # Zcash server port
  #zcashPort: 18232
  zcashPort: 7847

  # Zcash server username logs
  zcashUser: test

  # persistence directory
  zcashPassword: test

  updateInterval: 30

# verbose: provide log output
verbose: True

# redis host
redisHost: 192.168.1.79
# redis port
redisPort: 6379

minDiff: 1
startDiff: 1
maxDiff: 0
