name:                seal-pool
version:             0.1.0.0
github:              githubuser/seal-pool
license:             BSD3
author:              Author name here
maintainer:          example@example.com
copyright:           2019 Author name here

extra-source-files:
- README.md
# - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/seal-pool#readme>

dependencies:
- base >= 4.11 && < 10
- rio >= 0.1.8.0
- aeson
- attoparsec
- io-streams
- network
- tcp-streams
- http-client
- http-types
- text
- yaml
- bytestring
- string-random
- servant-server
- warp
- mtl
- base16-bytestring
- random
- memory
- cryptonite
- data-default
- lens
- time
#- async-timer


ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  dependencies:
  - db-redis
  default-extensions:
  - NoImplicitPrelude
  - OverloadedStrings
  - PatternSynonyms
  - ScopedTypeVariables
  - TypeApplications
  - ViewPatterns

internal-libraries:
  db-redis:
    source-dirs: db-redis
    dependencies:
    - hedis
    reexported-modules: DB.Redis as DB

executables:
  seal-pool-exe:
    main:                Main.hs
    source-dirs:         app
    dependencies:
    - seal-pool
    - db-redis
    - optparse-simple

    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

tests:
  seal-pool-test:
    main:                Spec.hs
    source-dirs:         test
    dependencies:
    - db-redis
    - seal-pool
    - hspec

    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
